// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admins": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получить список админов. Доступен фильтр по типу админа (superadmin или manager)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admins"
                ],
                "summary": "Получить список админов",
                "parameters": [
                    {
                        "type": "string",
                        "description": "тип получаемого админа (superadmin или manager)",
                        "name": "admin_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "полученный список админов",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/internal_features_admin_transport_http.AdminResponseDTO"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Создать нового админа в системе",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admins"
                ],
                "summary": "Создать админа",
                "parameters": [
                    {
                        "description": "CreateAdmin тело запроса",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_features_admin_transport_http.CreateAdminRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "успешно созданный админ",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_features_admin_transport_http.AdminResponseDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admins/auth": {
            "post": {
                "description": "Войти в аккаунт админа в системе",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admins"
                ],
                "summary": "Атворизоваться как админ",
                "parameters": [
                    {
                        "description": "LoginAdmin тело запроса",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_features_admin_transport_http.LoginAdminRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "успешно созданный токен авторизации",
                        "schema": {
                            "$ref": "#/definitions/internal_features_admin_transport_http.LoginAdminResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admins/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получить админа по ID из jwt после авторизации",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admins"
                ],
                "summary": "Получить админа",
                "responses": {
                    "200": {
                        "description": "полученный admin",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_features_admin_transport_http.AdminResponseDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admins/role/{id}": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Изменить тип админа в системе, может только superadmin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admins"
                ],
                "summary": "Изменить роль админа",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID обновляемого админа",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "PatchAdmin тело запроса",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_features_admin_transport_http.UpdateAdminTypeRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admins/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получить админа по ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admins"
                ],
                "summary": "Получить админа",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID получаемого админа",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "полученный admin",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_features_admin_transport_http.AdminResponseDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Изменить почту, имя, тип админа в системе",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admins"
                ],
                "summary": "Изменить админа",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID обновляемого админа",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "PatchAdmin тело запроса",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_features_admin_transport_http.AdminPatchRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "успешно измененный админ",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_features_admin_transport_http.AdminResponseDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/product-categories": {
            "get": {
                "description": "Получить список категорий, есть пагинация.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "product-categories"
                ],
                "summary": "Получить список категорий",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "лимит возвращаемых категорий",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "смещение возвращаемых категорий",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "полученные категории",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_features_product_categories_transport.ProductCategoryDTOResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/product-categories/{category_code}": {
            "get": {
                "description": "Получить категорию товаров по коду",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "product-categories"
                ],
                "summary": "Получить категорию товаров",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Код получаемой категории",
                        "name": "category_code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "полученная категория",
                        "schema": {
                            "$ref": "#/definitions/internal_features_product_categories_transport.GetProductCategoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Изменить категорию товаров (название и цену установки) в системе",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "product-categories"
                ],
                "summary": "Изменить категорию",
                "parameters": [
                    {
                        "type": "string",
                        "description": "код обновляемой категории (windows, entrance-doors, interior-doors, balconies, others)",
                        "name": "category_code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "PatchProductCategory тело запроса",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_features_product_categories_transport.PatchProductCategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "обновленная категория",
                        "schema": {
                            "$ref": "#/definitions/internal_features_product_categories_transport.PatchProductCategoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/products": {
            "get": {
                "description": "Получить список товаров, есть фильтры",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Получить список товаров",
                "parameters": [
                    {
                        "type": "string",
                        "description": "код категории товар (windows, entrance-doors, interior-doors, balconies, others)",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "лимит возвращаемых категорий",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "смещение возвращаемых категорий",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "сортировка по возрастанию или убыванию (asc, desc)",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список товаров",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_domain.ProductBaseDetailed"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Удалить несколько товаров по списку их ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Удалить товары",
                "parameters": [
                    {
                        "description": "DeleteProducts тело запроса",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_features_products_transport_http.ProductIdDTORequest"
                            }
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/products/image/{id}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Загрузить фото товара по ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Загрузить фото товара",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID товара",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "UploadProductImage тело ответа",
                        "schema": {
                            "$ref": "#/definitions/internal_features_products_transport_http.UploadProductImageResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Удалить фото товара по ID товара.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Удалить фото товара",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID товара для удаления фото",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/products/visibility": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Изменить видимость списка товаров по списку их ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Изменить видимость списка товаров",
                "parameters": [
                    {
                        "description": "UpdateProductsVisability тело запроса",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_features_products_transport_http.UpdateProductsVisabilityRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/products/visibility/p/{id}": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Изменить видимость товара",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Изменить видимость товара",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID обновляемой заявки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "UpdateProductVisability тело запроса",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_features_products_transport_http.UpdateProductVisabilityRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/products/{category_code}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Создать товар (требуется указать конкретную категорию)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Создать товар",
                "parameters": [
                    {
                        "type": "string",
                        "description": "код категории товар которой создается (windows, entrance-doors, interior-doors, balconies, others)",
                        "name": "category_code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "CreateProduct тело запроса, если category_code=others",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_domain.ProductBase"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Созданный товар",
                        "schema": {
                            "$ref": "#/definitions/internal_features_products_transport_http.CreateProductResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/products/{category_code}/{id}": {
            "get": {
                "description": "Получить товар (требуется указать конкретную категорию)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Получить товар",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID товара",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "код категории товар которой создается (windows, entrance-doors, interior-doors, balconies, others)",
                        "name": "category_code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Созданный товар",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_domain.ProductDetailed"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Обновить товар (требуется указать конкретную категорию)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Обновить товар",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID товара",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "код категории товар которой создается (windows, entrance-doors, interior-doors, balconies, others)",
                        "name": "category_code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "PatchProduct тело запроса",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_domain.ProductBasePatch"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Обновленный товар",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_domain.ProductBase"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/products/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Удалить товар по ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Удалить товар",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID товара",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/requests": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получить список заявок, есть фильтры.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "customer-requests"
                ],
                "summary": "Получить список заявок",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "фильтр по ID админа, обрабатывающего заявку",
                        "name": "admin",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "фильтр по статусу заявок",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "фильтр по номеру клиента в формате 79998887766",
                        "name": "customer",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "лимит возвращаемых заявок",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "смещение возвращаемых заявок",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "полученные заявки",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_domain.CustomerRequestForList"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Создать заявку клиента (не требует авторизации)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "customer-requests"
                ],
                "summary": "Создать заявку клиента",
                "parameters": [
                    {
                        "description": "CreateCustomerRequest тело запроса",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_domain.CustomerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "ID созданной заявки",
                        "schema": {
                            "$ref": "#/definitions/internal_features_customer_requests_transport_http.CustomerRequestIDResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/requests/status/{id}": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Изменить статус заявки (new, in_progress, completed, cancelled) в системе",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "customer-requests"
                ],
                "summary": "Изменить статус заявки",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID обновляемой заявки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "UpdateCustomerRequestStatus тело запроса",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_features_customer_requests_transport_http.UpdateReqStatusDTO"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/requests/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получить заявку по ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "customer-requests"
                ],
                "summary": "Получить заявку",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID получаемой заявки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "полученная заявка",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_domain.CustomerRequestDetailed"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Удалить заявку по ID. Может только superadmin",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "customer-requests"
                ],
                "summary": "Удалить заявку",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID удаляемой заявки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Изменить заявку (желаемые дату и время, доп. комментарий) в системе",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "customer-requests"
                ],
                "summary": "Изменить заявку",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "ID обновляемой заявки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "PatchCustomerRequest тело запроса",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_domain.CustomerRequestPatch"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/static/{path}": {
            "get": {
                "description": "Возвращает изображение по указанному пути. Поддерживает serve content.",
                "tags": [
                    "images"
                ],
                "summary": "Получить изображение",
                "parameters": [
                    {
                        "type": "string",
                        "format": "path",
                        "description": "Путь к изображению",
                        "name": "path",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Изображение успешно получено",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Неверный путь к изображению",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Изображение не найдено",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_nikitavaulin_kudesnik_internal_core_domain.CustomerRequest": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "customer_phone_number": {
                    "type": "string"
                },
                "desired_date": {
                    "type": "string"
                },
                "desired_time": {
                    "type": "string"
                },
                "extra_comment": {
                    "type": "string"
                },
                "handled_at": {
                    "type": "string"
                },
                "handler_admin_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "product_id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_domain.CustomerRequestStatus"
                }
            }
        },
        "github_com_nikitavaulin_kudesnik_internal_core_domain.CustomerRequestDetailed": {
            "type": "object",
            "properties": {
                "chosen_product": {
                    "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_domain.ProductBaseDetailed"
                },
                "created_at": {
                    "type": "string"
                },
                "customer_fullname": {
                    "type": "string"
                },
                "customer_phone_number": {
                    "type": "string"
                },
                "desired_date": {
                    "type": "string"
                },
                "desired_time": {
                    "type": "string"
                },
                "extra_comment": {
                    "type": "string"
                },
                "handled_at": {
                    "type": "string"
                },
                "handler_admin_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "product_id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_domain.CustomerRequestStatus"
                }
            }
        },
        "github_com_nikitavaulin_kudesnik_internal_core_domain.CustomerRequestForList": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "customer_fullname": {
                    "type": "string"
                },
                "customer_phone_number": {
                    "type": "string"
                },
                "desired_date": {
                    "type": "string"
                },
                "desired_time": {
                    "type": "string"
                },
                "handled_at": {
                    "type": "string"
                },
                "handler_admin_id": {
                    "type": "string"
                },
                "handler_admin_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_domain.CustomerRequestStatus"
                }
            }
        },
        "github_com_nikitavaulin_kudesnik_internal_core_domain.CustomerRequestPatch": {
            "type": "object",
            "properties": {
                "desired_date": {
                    "type": "string"
                },
                "desired_time": {
                    "type": "string"
                },
                "extra_comment": {
                    "type": "string"
                }
            }
        },
        "github_com_nikitavaulin_kudesnik_internal_core_domain.CustomerRequestStatus": {
            "type": "string",
            "enum": [
                "new",
                "in_progress",
                "completed",
                "cancelled"
            ],
            "x-enum-varnames": [
                "NewRequestStatus",
                "InProgressRequestStatus",
                "CompletedRequestStatus",
                "CancelledRequestStatus"
            ]
        },
        "github_com_nikitavaulin_kudesnik_internal_core_domain.ProductBase": {
            "type": "object",
            "properties": {
                "category_code": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "is_visible": {
                    "type": "boolean"
                },
                "price": {
                    "type": "number"
                },
                "producer_id": {
                    "type": "string"
                },
                "product_name": {
                    "type": "string"
                },
                "thumbnail_url": {
                    "type": "string"
                }
            }
        },
        "github_com_nikitavaulin_kudesnik_internal_core_domain.ProductBaseDetailed": {
            "type": "object",
            "properties": {
                "category_code": {
                    "type": "string"
                },
                "category_name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "installation_price": {
                    "type": "number"
                },
                "is_visible": {
                    "type": "boolean"
                },
                "price": {
                    "type": "number"
                },
                "producer_company_name": {
                    "type": "string"
                },
                "producer_id": {
                    "type": "string"
                },
                "product_name": {
                    "type": "string"
                },
                "thumbnail_url": {
                    "type": "string"
                }
            }
        },
        "github_com_nikitavaulin_kudesnik_internal_core_domain.ProductBasePatch": {
            "type": "object",
            "properties": {
                "category_code": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "is_visible": {
                    "type": "boolean"
                },
                "price": {
                    "type": "number"
                },
                "producer_id": {
                    "type": "string"
                },
                "product_name": {
                    "type": "string"
                },
                "thumbnail_url": {
                    "type": "string"
                }
            }
        },
        "github_com_nikitavaulin_kudesnik_internal_core_domain.ProductDetailed": {
            "type": "object",
            "properties": {
                "details": {
                    "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_domain.ProductDetails"
                },
                "product": {}
            }
        },
        "github_com_nikitavaulin_kudesnik_internal_core_domain.ProductDetails": {
            "type": "object",
            "properties": {
                "category_name": {
                    "type": "string"
                },
                "installation_price": {
                    "type": "number"
                },
                "producer_company_name": {
                    "type": "string"
                }
            }
        },
        "github_com_nikitavaulin_kudesnik_internal_core_domain.Role": {
            "type": "string",
            "enum": [
                "superadmin",
                "manager",
                "dismissed"
            ],
            "x-enum-varnames": [
                "AdminRole",
                "ManagerRole",
                "DismissedAdminRole"
            ]
        },
        "github_com_nikitavaulin_kudesnik_internal_core_transport_http_response.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_features_admin_transport_http.AdminPatchRequestDTO": {
            "type": "object",
            "properties": {
                "admin_type": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                }
            }
        },
        "internal_features_admin_transport_http.AdminResponseDTO": {
            "type": "object",
            "properties": {
                "admin_type": {
                    "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_domain.Role"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "internal_features_admin_transport_http.CreateAdminRequestDTO": {
            "type": "object",
            "properties": {
                "admin_type": {
                    "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_domain.Role"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "internal_features_admin_transport_http.LoginAdminRequestDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "internal_features_admin_transport_http.LoginAdminResponseDTO": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "internal_features_admin_transport_http.UpdateAdminTypeRequestDTO": {
            "type": "object",
            "properties": {
                "admin_type": {
                    "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_domain.Role"
                }
            }
        },
        "internal_features_customer_requests_transport_http.CustomerRequestIDResponseDTO": {
            "type": "object",
            "properties": {
                "customer_request_id": {
                    "type": "string"
                }
            }
        },
        "internal_features_customer_requests_transport_http.UpdateReqStatusDTO": {
            "type": "object",
            "properties": {
                "status": {
                    "$ref": "#/definitions/github_com_nikitavaulin_kudesnik_internal_core_domain.CustomerRequestStatus"
                }
            }
        },
        "internal_features_product_categories_transport.GetProductCategoryResponse": {
            "type": "object",
            "properties": {
                "category_code": {
                    "type": "string"
                },
                "category_name": {
                    "type": "string"
                },
                "installation_price": {
                    "type": "number"
                }
            }
        },
        "internal_features_product_categories_transport.PatchProductCategoryRequest": {
            "type": "object",
            "properties": {
                "category_name": {
                    "type": "string"
                },
                "installation_price": {
                    "type": "number"
                }
            }
        },
        "internal_features_product_categories_transport.PatchProductCategoryResponse": {
            "type": "object",
            "properties": {
                "category_code": {
                    "type": "string"
                },
                "category_name": {
                    "type": "string"
                },
                "installation_price": {
                    "type": "number"
                }
            }
        },
        "internal_features_product_categories_transport.ProductCategoryDTOResponse": {
            "type": "object",
            "properties": {
                "category_code": {
                    "type": "string"
                },
                "category_name": {
                    "type": "string"
                },
                "installation_price": {
                    "type": "number"
                }
            }
        },
        "internal_features_products_transport_http.CreateProductResponse": {
            "type": "object",
            "properties": {
                "category_code": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_visible": {
                    "type": "boolean"
                },
                "price": {
                    "type": "number"
                },
                "producer_id": {
                    "type": "string"
                },
                "product_name": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "internal_features_products_transport_http.ProductIdDTORequest": {
            "type": "object",
            "required": [
                "product_id"
            ],
            "properties": {
                "product_id": {
                    "type": "string"
                }
            }
        },
        "internal_features_products_transport_http.UpdateProductVisabilityRequestDTO": {
            "type": "object",
            "properties": {
                "is_visible": {
                    "type": "boolean"
                }
            }
        },
        "internal_features_products_transport_http.UpdateProductsVisabilityRequestDTO": {
            "type": "object",
            "properties": {
                "is_visible": {
                    "type": "boolean"
                },
                "productsIDs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_features_products_transport_http.ProductIdDTORequest"
                    }
                }
            }
        },
        "internal_features_products_transport_http.UploadProductImageResponseDTO": {
            "type": "object",
            "properties": {
                "image_url": {
                    "type": "string",
                    "example": "uploads/products/1778765484773106300_90c1e8db-4a4a-44c3-961a-6ad2c4b043f6.jpg"
                },
                "thumbnail_url": {
                    "type": "string",
                    "example": "uploads/products/1778765484773106300_90c1e8db-4a4a-44c3-961a-6ad2c4b043f6.jpg"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Some queries require authorization: \"Bearer \u003cjwt_token\u003e\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:5050",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Kudesnik API",
	Description:      "Kudesnik. Windows & Doors | REST-API scheme",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
